mongo:
  image: mongo

mongo-seed:
  build: ./data
  links:
  - mongo

restaurants-api:
  build: .
  links:
  - mongo
  ports:
  - 8080:8080
  environment:
  - MONGO_URI=mongodb://mongo:27017/restaurants